version: "3"
services:
  crond:
    build:
      context: .
      dockerfile: docker/crond/Dockerfile
    restart: always
    network_mode: host
    environment:
      HOST: "localhost"
      PORT: "8080"
    volumes:
      - "./docker/crond/config.json:/opt/crontab/config.json"
      - "./docker/crond/logs:/var/log/crontab"
      - "/var/run/docker.sock:/var/run/docker.sock"
